#ifndef _SDL_keysym_h_compat
#define _SDL_keysym_h_compat

#include <SDL2/SDL_keycode.h>
#include <SDL2/SDL_scancode.h>

typedef SDL_Keycode SDLKey;

#define SDLK_KP0 SDLK_KP_0
#define SDLK_KP1 SDLK_KP_1
#define SDLK_KP2 SDLK_KP_2
#define SDLK_KP3 SDLK_KP_3
#define SDLK_KP4 SDLK_KP_4
#define SDLK_KP5 SDLK_KP_5
#define SDLK_KP6 SDLK_KP_6
#define SDLK_KP7 SDLK_KP_7
#define SDLK_KP8 SDLK_KP_8
#define SDLK_KP9 SDLK_KP_9
#define SDLK_LMETA SDLK_LGUI
#define SDLK_RMETA SDLK_RGUI
#define SDLK_PRINT SDLK_PRINTSCREEN
#define SDLK_SCROLLOCK SDLK_SCROLLLOCK
#define SDLK_NUMLOCK SDLK_NUMLOCKCLEAR

enum {
    SDLK_WORLD_0 = 160,
    SDLK_WORLD_1, SDLK_WORLD_2, SDLK_WORLD_3, SDLK_WORLD_4, SDLK_WORLD_5,
    SDLK_WORLD_6, SDLK_WORLD_7, SDLK_WORLD_8, SDLK_WORLD_9, SDLK_WORLD_10,
    SDLK_WORLD_11, SDLK_WORLD_12, SDLK_WORLD_13, SDLK_WORLD_14, SDLK_WORLD_15,
    SDLK_WORLD_16, SDLK_WORLD_17, SDLK_WORLD_18, SDLK_WORLD_19, SDLK_WORLD_20,
    SDLK_WORLD_21, SDLK_WORLD_22, SDLK_WORLD_23, SDLK_WORLD_24, SDLK_WORLD_25,
    SDLK_WORLD_26, SDLK_WORLD_27, SDLK_WORLD_28, SDLK_WORLD_29, SDLK_WORLD_30,
    SDLK_WORLD_31, SDLK_WORLD_32, SDLK_WORLD_33, SDLK_WORLD_34, SDLK_WORLD_35,
    SDLK_WORLD_36, SDLK_WORLD_37, SDLK_WORLD_38, SDLK_WORLD_39, SDLK_WORLD_40,
    SDLK_WORLD_41, SDLK_WORLD_42, SDLK_WORLD_43, SDLK_WORLD_44, SDLK_WORLD_45,
    SDLK_WORLD_46, SDLK_WORLD_47, SDLK_WORLD_48, SDLK_WORLD_49, SDLK_WORLD_50,
    SDLK_WORLD_51, SDLK_WORLD_52, SDLK_WORLD_53, SDLK_WORLD_54, SDLK_WORLD_55,
    SDLK_WORLD_56, SDLK_WORLD_57, SDLK_WORLD_58, SDLK_WORLD_59, SDLK_WORLD_60,
    SDLK_WORLD_61, SDLK_WORLD_62, SDLK_WORLD_63, SDLK_WORLD_64, SDLK_WORLD_65,
    SDLK_WORLD_66, SDLK_WORLD_67, SDLK_WORLD_68, SDLK_WORLD_69, SDLK_WORLD_70,
    SDLK_WORLD_71, SDLK_WORLD_72, SDLK_WORLD_73, SDLK_WORLD_74, SDLK_WORLD_75,
    SDLK_WORLD_76, SDLK_WORLD_77, SDLK_WORLD_78, SDLK_WORLD_79, SDLK_WORLD_80,
    SDLK_WORLD_81, SDLK_WORLD_82, SDLK_WORLD_83, SDLK_WORLD_84, SDLK_WORLD_85,
    SDLK_WORLD_86, SDLK_WORLD_87, SDLK_WORLD_88, SDLK_WORLD_89, SDLK_WORLD_90,
    SDLK_WORLD_91, SDLK_WORLD_92, SDLK_WORLD_93, SDLK_WORLD_94, SDLK_WORLD_95
};

#endif
